version: "2.3"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - "13306:3306"
    volumes:
      - "/DevEnv/Compilers/ElevatorDriver/mysql_data:/var/lib/mysql"

  srv-config:
    image: edu2021/srv-config:latest
    container_name: srv-config
    environment:
      - APP_ENV=dev
    ports:
      - "16002:6002"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:6002/actuator/health" ]
      timeout: 10s
      retries: 3
    depends_on:
      mariadb:
        condition: service_started

  api-admin:
    image: edu2021/api-admin:latest
    container_name: api-admin
    environment:
      - APP_ENV=dev
      - config.server.path=http://srv-config:6002
    ports:
      - "16060:6060"
      - "17010:7010"
    depends_on:
      srv-config:
        condition: service_healthy

  api-cabin-floor:
    image: edu2021/api-cabin-floor:latest
    container_name: api-cabin-floor
    environment:
      - config.server.path=http://srv-config:6002
    ports:
      - "16070:6070"
    depends_on:
      srv-config:
       condition: service_healthy

  api-engine:
    image: edu2021/api-engine:latest
    container_name: api-engine
    environment:
      - config.server.path=http://srv-config:6002
    ports:
      - "16050:6050"
    depends_on:
      srv-config:
       condition: service_healthy
