server:
  port: 6060
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_admin
    username: root
    password: admin123
  liquibase:
      enabled: true
      change-log: classpath:/db/db.changelog.xml
      default-schema: api_admin