server:
  port: 6060
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/testdb
    username: root
    password: admin123
  liquibase:
      enabled: true
      change-log: classpath:/db/db.changelog.xml
      default-schema: testdb