server:
  port: 6002
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuration
  profiles:
    active: native
  security:
    user:
      name: ${config.server.username:1}
      password: ${config.server.password:2}
      role: SYSTEM

