server:
  port: 6050
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mongodb://localhost:27017/api_engine
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog.xml
    default-schema: api_engine
waitingStrategy:
  #type: Possible Values: JobQuartz, FutureTask
  type: JobQuartz
  time: 5000
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration