server:
  port: 7010
spring:
  datasource:
    url: jdbc:mysql://mariadb:3306/api_admin?enabledTLSProtocols=TLSv1.2&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin123

